### ISSUE TITLE
Are there any plans to port to ROS2? 

### ISSUE THREAD

**Issue by Ekanshh** [HoangGiang93/mujoco_sim#24]
Thank you for this amazing project! 💯

I was wondering if there are any plans to support ROS2 in this project? If not, what modifications would be necessary to integrate it with ROS2?

**Comment by HoangGiang93** [comment]
Thank you for your question. There are no plans to support ROS2 in this project, because ROS2 is still in development and each Ubuntu version can only support a subset of ROS2 versions, hence there is no stable API overall to make it practically useful for me yet. Most of people I know still use Ubuntu <= 20.04.
However, I'm developing a new framework that support both ROS and ROS2 and other simulations as well. It's heavier than this project, but it does a lot more. Please check out this [repo](https://github.com/Multiverse-Framework/Multiverse).
